project:
  type: website
  output-dir: docs

website:
  title: "Ren SATO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: achievement.qmd
        text: Achievement
    right:
      - text: JP
        menu:
          - href: index.qmd
            text: Home
          - href: achievement.qmd
            text: Achievement
      - text: EN
        menu:
          - href: index-en.qmd
            text: Home
          - href: achievement-en.qmd
            text: Achievement

format:
  html:
    theme: cosmo
    toc: false