project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: Home
        menu:
          - href: index.qmd
            text: Jp
          - href: index-en.qmd
            text: En
      - text: Achievement
        menu:
          - href: achievement.qmd
            text: Jp
          - href: achievement-en.qmd
            text: En

format:
  html:
    theme: cosmo
    toc: false