project:
  type: website
  output-dir: docs

website:
  title: "佐藤 蓮"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: achievement.qmd
        text: Achievement

format:
  html:
    theme: cosmo
    toc: false