---
title: "Achievement"
lang: ja
---

## 論文

<ol reversed start="4">
  <li>Furukawa, Y., Sato, R., Fukaya, N., Kajitani, T., Katashima, T., & Sugiyasu, K. “Linear and Branched Supramolecular Polymers Formed from Isomeric Monomers as Revealed by Solution Viscoelasticity.” Chemical Science. Accepted (2026).</li>

  <li>Sato, R., Yamagata, Y., Araida, M., Sato, T., Naito, M., Sekiguchi, H., Akada, K., Chung, U., & Katashima, T. “Strain Amplitude Sweep Testing of Oscillatory Shear of Transient Networks with Controlled Network Structures.” [Science and Technology of Advanced Materials, 2613918 (2026).](https://www.tandfonline.com/doi/full/10.1080/14686996.2026.2613918)</li>

  <li>Cho, R., Kamata, H., Tsuji, Y., Fujisawa, A., Miura, Y., Ishikawa, S., Sato, R., Katashima, T., Sakai, T., & Fujishiro, M. “Optimizing a Self-Solidifying Hydrogel as an Endoscopically Deliverable Hydrogel Coating System: A Proof-of-Concept Study on Porcine Endoscopic Submucosal Dissection-Induced Ulcers.” [Polymer Journal, 1–9 (2024).](https://doi.org/10.1038/s41428-024-00921-w)</li>

  <li>Yamamoto, Y., Yamagata, Y., Sato, T., Nakamura, K., Sato, R., Naito, M., Chung, U., & Katashima, T. “Elucidating Nonlinear Stress Relaxation in Transient Networks through Two-Dimensional Rheo-Optics.” [ACS Macro Letters, 13(9), 1171–1178 (2024).](https://doi.org/10.1021/acsmacrolett.4c00338)</li>
</ol>

## 発表

<ol reversed start="13">
  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島拓弥「モデル材料を用いた触覚・行動のレオロジー特性依存性」第30回東日本支部・関東地区レオロジー研究会修士論文発表会 DIC本社 2026年3月 (口頭発表)</li>

  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島拓弥「構造を系統制御したモデル粘弾性液体を用いた触感の分析」第73回レオロジー討論会 P81 アオーレ長岡 2025年10月 (ポスター発表)</li>

  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島 拓弥「構造を系統制御したモデルソフトマターを用いた触感の分析」日本心理学会 第89回大会 3B-006-PH 東北学院大学 2025年9月 (ポスター発表)</li>

  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島 拓弥「系統制御したモデル過渡的網目を用いた触感因子の分析」日本レオロジー学会 第52年会 P25 東京大学 2025年5月 (ポスター発表)</li>

  <li>○佐藤 蓮・古川 悠布香・片島拓弥・深谷 菜摘・杉安和憲「超分子ポリマー準希薄溶液の線形粘弾性」関東高分子若手研究会 学生発表会・交流会2024 PM-15 東京大学 2025年3月 (ポスター発表)</li>

  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島拓弥「モデル粘弾性液体を用いた触覚尺度の構成とレオロジー特性依存性」第29回東日本支部・関東地区レオロジー研究会修士論文発表会及び第65回関東地区レオロジー研究会 明治大学 2025年3月 (口頭発表)</li>

  <li>○Ren Sato, Riho Fujikura, Ung-il Chung, Etsuko Haryu, Yukiko Muramoto, Takuya Katashima “Relationships between rheological properties and tactile sensory using viscoelastic liquids with controlled network structures” Symposium on Life Science Technologies, Aalto University, Espoo, Finland, January 2025. (口頭発表)</li>

  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島拓弥「構造を精密に制御した過渡的網目を用いた触感とレオロジー特性の相関解明」第2回日本化粧品技術者会学術大会 P1-26 神戸国際会議場 2024年11月 (ポスター発表)</li>

  <li>○佐藤 蓮・藤倉 璃保・針生 悦子・村本 由紀子・鄭 雄一・片島拓弥「精密に構造を制御した過渡的網目を用いた触り心地とレオロジー特性の相関」第72回レオロジー討論会 2F02 山形テルサ 2024年10月 (口頭発表)</li>

  <li>佐藤 蓮・鄭 雄一・片島 拓弥「構造を精密に制御した過渡的網目を用いた触感に及ぼすレオロジー特性の影響解明」日本レオロジー学会 第51年会 P38 名古屋工業大学 2024年5月 (ポスター発表)</li>

  <li>○佐藤 蓮・鄭 雄一・片島 拓弥「精密に構造制御したモデル粘弾性液体を用いた、触感に及ぼすレオロジー特性の影響」関東高分子若手研究会 学生発表会・交流会2024 PB-11 東京大学 2024年3月 (ポスター発表)</li>

  <li>○佐藤 蓮・鄭 雄一・片島 拓弥「Effect of rheological properties on texture using well-controlled transient networks」第28回東日本支部・関東地区レオロジー研究会修士論文発表会及び第64回関東地区レオロジー研究会 明治大学 2024年3月 (口頭発表)</li>

  <li>○佐藤 蓮・鄭 雄一・片島 拓弥「構造を精密に制御された過渡的網目を用いたレオロジー特性と触覚の相関解明」第35回高分子ゲル研究討論会 P6 東京大学 2023年1月 (ポスター発表)</li>
</ol>

## 受賞

1. 2026年度 東京大学大学院工学系研究科バイオエンジニアリング専攻修士課程 専攻長賞